version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=10 # Poll every 10 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  your-pipeline:
    image: deecaad/your-pipeline
    ports:
      - 8080:8080
    container_name: your-pipeline
